"""Remove animation_type column from story_segments

Revision ID: 53deb21697bb
Revises: 
Create Date: 2025-07-11 14:29:50.776451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53deb21697bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_segments', schema=None) as batch_op:
        batch_op.drop_column('animation_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animation_type', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
