"""Rename image_path to media_path in story_segments table

Revision ID: 672347280c1b
Revises: 5906d74cfbbc
Create Date: 2025-09-12 14:07:16.185584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672347280c1b'
down_revision = '5906d74cfbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_path', sa.String(length=256), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('media_path')

    # ### end Alembic commands ###
